### PR TITLE
2.2: Allow linking and jumping to admin panel tabs via anchors + apply button jump to current tab

### PR DESCRIPTION
**Pull request by jhli**
Based on http://stackoverflow.com/a/10787789
Required for persistent apply views see http://codetunnel.io/how-to-persist-url-hash-fragments-across-a-login-redirect/

### CODE REVIEW

**Comment by jhli** [comment]
Updated to feature redirecting if "apply" was hit rather than a regular save or save and new.
Open: Would be great there was a way to let the developer add more tabs like hitting "next" and "previous" for wizard style tabs.

**Comment by jhli** [comment]
Apply feature is part of this PR: https://github.com/croogo/croogo/pull/633

**Comment by rchavik** [comment]
Merged with some adjustments.

Thank you.

**Comment by jhli** [comment]
Great :).

**Comment by rchavik** [comment]
Sometimes I'm getting some blackholed requests.  I'm not very sure what the cause is, but reverting the merge seems to solve the problem.

It might have to do something with our meddling with the form action value.

Can you help investigate?

**Comment by rchavik** [comment]
Please ignore previous comment.

Related #652

**Pull request closed without merging**
