### PR TITLE
Elbakai patch 2

### PR DESCRIPTION
**Pull request by elbakai**

### CODE REVIEW

**Comment by rchavik** [comment]
Is this PR about the last commit 7874c2f?

In the future please only provide the intended change via a separate branch so that I don't have to guess which commit.

Note: I think your fork has diverged from upstream, so please ensure your branch really use the same master branch as upstream's master.

**Comment by elbakai** [comment]
OK i will do;
yes about 7874c2f,

**Comment by rchavik** [comment]
I have modified 7874c2f as 19c10b5c.

Thanks for the fix. Good catch.

**Comment by rchavik** [comment]
Sorry, force pushed commit as 4a1602d5.  The previous one contains incorrect issue id.

**Pull request closed without merging**
