### PR TITLE
add clearfix class

### PR DESCRIPTION
**Pull request by elbakai**
Add clearfix class to prevent float affect

### CODE REVIEW

**Comment by rchavik** [comment]
Can you provide a before and after screenshot so we can see the effect of this fix?

**Comment by elbakai** [comment]
look at the filter bar
<h2>After</h2>

capture d ecran 2015-10-19 a 02 17 05

<h2>Before</h2>

capture d ecran 2015-10-19 a 02 15 45

**Comment by elbakai** [comment]
the same problem in all filter bar

**Comment by rchavik** [comment]
I can't seem to reproduce this problem: 

full-width

That was tested using the tip of master v2.2.2-10-g4d8cc08

**Comment by fahad19** [comment]
instead of adding `clearfix` class to HTML, why not extend the existing CSS rule instead? like:

```css
.filter {
  .clearfix(); // mixin from Bootstrap
}
```

**Comment by rchavik** [comment]
Closing due inactivity and works-for-me

**Pull request closed without merging**
