### PR TITLE
2.3 - TBS 3 admin theme

### PR DESCRIPTION
**Pull request by mtancoigne**
After one week fighting with git, trying and experimenting things, here is a "nice" PR with the following changes :
- Updated to Bootstrap 3.3.1 (last version today)
- Updated admin LESS files
- Updated Croogo's plugins admin views
- Updated some Croogo's helpers
- Updated fontAwesome to 4.2 (last version today)
- Updated JS libraries to work with latest jQuery (1.11.2 today) as min 1.9 was needed for Twitter bootstrap.
- Minified JS libs
- Updated some test to fit with FA icons

I know it's still not passing Travis tests, and assets generation using the makefile fails too.

I used lessc 1.4.2 and yui-compressor to compile LESS and minimize CSS and LESS.

Be careful, now, the main CSS is named **admin.min.css**, wich is compressed. 

Have fun and we all are Charlie.

### CODE REVIEW

**Comment by rchavik** [comment]
I'm going to merge this into a separate branch as there are a few things I'd want change before getting it into mainline. But this is an insanely cool work Manuel.

Thank you!!! :beers:

**Comment by mtancoigne** [comment]
No problem :)

**Comment by rchavik** [comment]
TODO:

- [ ] Inconsistent color in the breadcrumb
- [ ] Headings being displayed (The `h2` tag in the view should only be displayed in small screen)
- [ ] Weird margin/padding size in the main admin area
- [ ] Inconsistent width in the sidebar icons, eg: the "Media" menu is indented too much.
- [ ] Need to port color for acl permissions table

**Comment by mtancoigne** [comment]
I hope to ne back on scene in the coming weeks and continue the work... I miss development a lot :-(

**Comment by rchavik** [comment]
hi @mtancoigne that's cool!

@LuMAXW3B might have started on any of those items, though.  So maybe leave a note here if you're going to start something.

Thanks

**Pull request closed without merging**
