### PR TITLE
Hook Admin Action

### PR DESCRIPTION
**Pull request by fbalarin**
Implements the possibility of hooking an action button that will appear on the view´s top actions

### CODE REVIEW

**Comment by rchavik** [comment]
Hello,

Thanks for this.  However I'm not convinced that this is needed.  In most cases, when we do add hooks, we would want to include some form fields. This can already be done via `Croogo::hookAdminTab()`.  

In the element hooked via `hookAdminTab()`, we can already add buttons to the `actions` block, eg:

```php
// Plugin/Foo/Config/bootstrap.php
Croogo::hookAdminTab('Nodes/admin_edit', 'Custom Fields', 'Foo.custom_fields');

// Plugin/Foo/View/Elements/custom_fields.ctp
$this->append('actions');
<button>My new button</button>
$this->end();

echo $this->Form->input('custom_field');
...
```

 @croogo/contributors, What do you guys think?

**Comment by dakota** [comment]
While I think this is something useful, like @rchavik pointed out, it's already possible.

**Comment by fbalarin** [comment]
For a record level context I agree. But what about the entity level? (Index view)? For example,access to import/export/sync operations. Like the add button, those operations are not related to a particular record to be on the row action or a tab on edit view. What do you think? Is there a better place to put those kind of operations?

**Comment by rchavik** [comment]
You can hook a helper to the desired Controller, eg:

```php
// Plugin/Foo/Config/bootstrap.php
Croogo::hookHelper('Nodes', 'Foo.AddButton');

// Plugin/Foo/View/Helper/AddButtonHelper.php
class AddButtonHelper extends AppHelper {
    public function beforeRender($viewFile) {
      $this->_View->append('actions', $this->_View->Form->button('hello') . ' ');
    }
}
```

I agree that it's not obvious to do.  Maybe it's worth adding then.  But I dislike having to modify so many view files. Maybe we could add `CroogoHelper::addAdminButton()` instead of doing it in `Croogo` class.

**Comment by fbalarin** [comment]
I was just following the same logic applied to the adminRowActions. The reason to modify so many views is that, in the way the common views are implemented we can´t extend those areas.
I think that using: 
`$this->assign('actions', $some_actions);`
or 
`$this->start('actions');
...
$this->end();`
That should replace the "actions" area on the view, but using:
`
$this->start('actions');
...
$this->end();`
should extend its content. 
But this concept is not being respected by the common views, it only generate the "common action" if "actions" is blank. What do you think?

**Comment by rchavik** [comment]
I think this is worth pursuing via another approach.  Keeping this open, but moving to 2.3.

**Comment by rchavik** [comment]
Accidentally closed when branch is deleted

**Comment by rchavik** [comment]
Recreated in #792

**Pull request closed without merging**
