### PR TITLE
Add ability to set paginate->order from params

### PR DESCRIPTION
**Pull request by phpMagpie**
Makes sense that if you can set default paginate->limit value from params (using nodes_per_page) you should also be able to set the default paginate->order value.  May want to change the name of the params variable used to sort_order or something more specific to its use case.

### CODE REVIEW

**Comment by phpMagpie** [comment]
Any chance this can be merged?

**Comment by rchavik** [comment]
Done.

Thanks again Paul.

**Comment by phpMagpie** [comment]
Thank you ... one less core hack I need in my code :)

**Comment by rchavik** [comment]
Actually, this was merged in bbabae7b63a16fb3b6158deb216a0c775b38f75e

**Comment by phpMagpie** [comment]
Sorry, it was ... I did not get notification of various pull requests getting merged and this is one of those.

**Comment by rchavik** [comment]
Yeah. It was rebased, thus it has a different sha1.

**Comment by phpMagpie** [comment]
OK, sorry for confusion.

**Pull request merged**
