### PR TITLE
RFC: Fixed public authorization not working

### PR DESCRIPTION
**Pull request by Wouter0100**
When a visitor came to a Croogo website, he was always redirected to the login page, because public authorization was always false due a new path. I've now used the Role alias to match it, now we're also not bind to any Aro id.

### CODE REVIEW

**Comment by Wouter0100** [comment]
Could the label RFC be added? I'm not sure if we should remove this method. I think it's good to use aliases instead of ID's though.

**Comment by Marlinc** [comment]
@Wouter0100 could you please rebase this against 3.0?

**Comment by Wouter0100** [comment]
Whoow... Okay. :p

**Comment by Wouter0100** [comment]
Rebased against 3.0, @Marlinc

**Comment by Wouter0100** [comment]
When you guys agree with this change, can it be merged?

**Pull request merged**
