### PR TITLE
Enhancement: Use saveAssociated in Users.admin_add/edit

### PR DESCRIPTION
**Pull request by phpMagpie**
Requesting a change for Users.admin_add/edit to use saveAssociated, so plugins can extend the core to save extra associated fields.

Related to https://github.com/croogo/croogo/issues/618

### CODE REVIEW

**Comment by jhli** [comment]
It is part of this PR already: https://github.com/croogo/croogo/pull/633

**Comment by rchavik** [comment]
jhli, isn't 634 about templates only?

**Comment by jhli** [comment]
Yes but it contains croogo cake bake templates that feature code like this:
https://github.com/croogo/croogo/pull/634/files#diff-3a46fa9663301c2d67fd0eb5ddc46c2bR59

**Comment by jhli** [comment]
My fault, but 634 only patches the same feature to the bake templates, as for this feature:

Should this not be changed for almost all core controller's admin edit/add methods?

**Comment by rchavik** [comment]
Both PR now merged.

Thanks a lot Paul!

**Pull request closed without merging**
