### PR TITLE
4.0 sleek

### PR DESCRIPTION
**Pull request by rchavik**
Initial WIP code for updating core theme with sleek dashboard.

sleek css/js NOT in this PR yet.

Current changeset addresses #395 which is a much readable code for generating the admin sidebar.

image

### CODE REVIEW

**Comment by dakota** [comment]
Codewise looks ok, but the sleek css and js files are missing :)

**Comment by rchavik** [comment]
Sorry, I meant to say is not in thid PR. But it's a straight up copy from its dist folder

**Comment by rchavik** [comment]
Jan 14th 2020

**Comment by rchavik** [comment]
@dakota this branch uses cdn for now. you should be able to preview them locally.

**Comment by rchavik** [comment]
Can also be previewed [here](http://demo.croogo.org/4.0/admin/)

**Comment by rchavik** [comment]
I'm thinking of ditching this.

Some issue with the sidebar when changing width. Not sure if I want to spend time on this.

**Comment by rchavik** [comment]
I'll see if I can port the helper to master.

**Pull request closed without merging**
