### PR TITLE
Fix: add validate unique slug for terms

### PR DESCRIPTION
**Pull request by PofMagicfingers**
Hello :wave: 

Without this fix, when you try to enter the same slug for two terms it crashes (500 internal error) with a SQL constraint error.

Pof.

### CODE REVIEW

**Comment by PofMagicfingers** [comment]
Will you merge this PR ?

**Comment by rchavik** [comment]
Sorry, I missed this.  Can you rebase on top latest master?

Thanks

**Comment by PofMagicfingers** [comment]
Rebased with master (with pain but diff looks good)

**Comment by rchavik** [comment]
Sorry.   I meant a simple `git rebase origin/master` so that only your commit is shown.

I will directly adjust.

**Comment by rchavik** [comment]
Thanks. 

I have rebase and commited your changes.

I recommend to use a separate branch for this type of fixes and try to keep master in sync with upstream.

**Comment by PofMagicfingers** [comment]
Yep, that exactly what we do, and rebase is what I tried to do, but rebase accross different origin (here, forks) are trickier and result was messy... :-(

Have you tried the rebase and merge option ?
https://blog.github.com/2016-09-26-rebase-and-merge-pull-requests/

**Comment by rchavik** [comment]
No I haven't.

I normally use the CLI unless the PR is really simple

**Pull request closed without merging**
