### PR TITLE
[WIP] Use CRUD for 3.0

### PR DESCRIPTION
**Pull request by Marlinc**

### CODE REVIEW

**Comment by dakota** [comment]
Any objections to merging this into 3.0 so long?

**Comment by Wouter0100** [comment]
Omg. Nice. Can't wait till this is merged in 3.0.

**Comment by Marlinc** [comment]
Thanks a lot for the continued work @dakota! Lets see what @rchavik has to say and then I think we can start merging it in so that we can continue development on the 3.0 branch

**Comment by rchavik** [comment]
please go ahead with the merge once you feel it's ready

**Comment by dakota** [comment]
I think this is in a mergeable state now. Most of the previous commits had very little to do with crud. I think all the crud conversions are complete.

**Comment by Marlinc** [comment]
Very nice!

**Pull request merged**
