### PR TITLE
Improve FileManager plugin by adapting xintesa/assets

### PR DESCRIPTION
**Pull request by rchavik**

### CODE REVIEW

**Comment by miketallroth** [comment]
I'm stuck in trying to review this PR. I did a fresh install with source, then checked out the 3.1-assets branch, and cleared out a couple of problems I'm already aware of (and I owe croogo/croogo a PR on those). But once past all that, I still get an error saying "Table assets.asset_usages" doesn't exist. I'm trying to run the migration in the FileManager plugin that appears to contain the missing table, but I'm unable to successfully run it.

When I try to run "cake Croogo upgrade migrations", I get a "Class Croogo\Core\Shell\Task\CroogoPlugin" not found error. Maybe the Croogo shell has not been upgraded for the 3.x branches?

Without that however, I don't know how to execute the migration to load the missing table. Is there a way I can just point to the migration file itself and direct execute it?

**Comment by miketallroth** [comment]
Changed my install process to do the composer step with source, then checked out the 3.1-assets branch, then completed the Croogo.Install install step. This got me going much faster, but I still ran into the same problems with the plugin. Local adapter seems to be missing, even using the Legacy adapter doesn't produce an error, but doesn't seem to actually upload the file either.

Feels like I'm just not setting up the app correctly in this situation.

**Comment by rchavik** [comment]
Hi Mike.  Thanks for looking into this PR.

> Changed my install process to do the composer step with source, then checked out the 3.1-assets branch, then completed the Croogo.Install install step. This got me going much faster, but I still ran into the same problems with the plugin. Local adapter seems to be missing, even using the Legacy adapter doesn't produce an error, but doesn't seem to actually upload the file either.

As you might have found out, this PR currently does not address upgrade path yet.

Therefore, in order to test, after `composer install`, you will need to start using an empty database and run the installer with the `3.1-asset` branch already checked out. 

I can't recall if the CLI installer works with this PR yet.  Before replying here, I tested with the web installer.

> I'm a little confused about the proper location for the files, whether they should be in webroot/uploads, webroot/attachments, or webroot/assets.

I tried to be backward compatible (which might not be wise here).  Maybe we should get rid of the `LegacyLocalAttachment` storage config later (see `FileManager/config/bootstrap.php`).
Moving forward, we should pick one of those 3.

In the current state, target upload directory is `webroot/assets`.

**Comment by miketallroth** [comment]
Thanks for the comments, they helped push through to get things working. I've attached my install script which automates setting up a new project for testing. Here are the two main things I found were not in order in my environment to complete the install;

1. The intervention/image and league/flysystem are required in the croogo/croogo library, but not yet in the croogo/app, so they needed to be manually required there,
2. xintesa/Assets requires the PHP GD module, which my 16.04 environment didn't have by default.

I did confirm that the CLI install does work, and that your logic w/r/t the Local vs Legacy Adapters makes sense. My confusion in trying to get things to work was making me question everything. It was actually the myriad other things I wasn't getting right that prevented me from succeeding.

Now that I've had a chance to run it, and think through how its used, I've got some comments, which I'll put in a subsequent post.

[install-croogo-test-branch.txt](https://github.com/croogo/croogo/files/2463038/install-croogo-test-branch.txt)

**Comment by miketallroth** [comment]
Hi Rachman,

After having used it now for a few days, I really like it. There are a couple confusing points which I'll try to explain, and maybe some minor bugs here and there, but overall it looks and feels great. It will be a nice upgrade to Croogo.

I've included lots of comments below, so I apologize for the length. I thought about breaking this up into multiple posts, but not sure that would help much. Also, if my wording is too strong, please know these are suggestions only. I could be thinking about this differently than what you intended, so I might need to have my viewpoint adjusted.

**I'll start with the more conceptual items:**

Icons for delete and un-register are a little inconsistent. In some cases the trashcan means delete, and in others it means un-register (ref. the Node > Asset tab). IMHO, the trashcan should always mean delete from the system (or maybe to the recycle bin if there was one). But un-register should use a different icon. Maybe since registering an existing asset with a new content item is performed with the '+' icon, then un-registering from a content item should be done with the '-' icon, not the trashcan. I'm not up to speed on FontAwesome, but it looks like there is an fa-minus to go with the fa-plus.

There is a paperclip icon that keeps coming up for me as I navigate through the browsers, uploaders, etc. I believe this is supposed to be present when we are using the wysiwyg editor, but not in this context. The simplest way to see what I'm describing is to go to a Node that already has an asset registered. Click the Upload button, then in the popup window, click the Publishing > Cancel button. The popup window then goes to another asset browser. Before moving on, notice that the url contains a query param "editor=1". Next, click on List All Attachments, notice the "editor=1" is gone, then click on List Attachments, and the paperclip is now gone. So, it only shows up in the load immediately after the upload window. (Also note this happens both if you Cancel the previous page, or if you hit the Upload button after queuing up an attachment or two. Its just simpler to demonstrate by canceling.)

Additionally in this flow, the trashcan appears in the popup when you are viewing the list of attachments registered with this content item. In this context, it seems the trashcan should be hidden. It feels like it should just un-register the asset from the content item, however it actually deletes it. The trashcan should be hidden, and the fa-minus should be there as an un-register button.

Further along the lines of what should be able to be done where. To help ensure the user doesn't delete something by mistake, the delete action should not be possible in the content-related browsers. The delete should only be possible from the Media > Attachments browser. The upload, register and un-register should all be available from the content-related browsers, but delete should be protected. One case in particular that I'm thinking about is when you have an asset registered with several different nodes, and you want to un-register it from just one of the nodes. If you were to click on this trashcan thinking it was the un-register action, you would have just removed it from all the nodes, and deleted it from the system. Whoops.

One thing on the database side of things. I see the path field is consistent between the parent and the child asset, using the hashed version of the name in both cases. In contrast, the filename field uses the original filename for the parent, but a hashed version for the child. It might make sense for the filename field to be consistent between both parent and child as well. Here's my thinking;

```
id, p_a_id, filename,                 path
1,  NULL,   logo3.gif,                /assets/01/02/03/longhash.gif
2,  1,      logo3.resized-100x48.gif, /assets/01/02/03/longhash.resized-100x48.gif
```

**The rest of these feel like minor bugs / issues:**

Back to the content-related asset list in the Node > Asset tab. When the node is first loaded, and you go to the Asset tab, the hover tooltips work fine. But after you click the Reload button, the tooltips do not work anymore. Looks like some javascript gets disabled after the Reload. I don't see any JS errors in the console, but that's as far as I dug into that one.

On a related note, in the List All Attachments popup browser, the tooltips seem to work for all the image based icons, but not for the FA icons. So, the fa-plus doesn't get a tooltip. It would be nice if it did, this had me confused, especially with the paperclip appearing once in a while. I wasn't sure how to register an existing asset to a node.

When displaying the List All Attachments browser, it might be useful to see a count of the number of usages for a particular asset (or parent asset). Related to some comments above, when deciding if you are going to actually delete an asset, it would be nice to know if its still being used in another content item. This should only be necessary in the Media > Attachments browser, not necessarily the content-related browser.

The number of versions field is empty in the browser. It only shows up when you use the content-related browser. I'm guessing this is intended to be the number of resized versions plus one for the original?

Is there a way to delete just one of the resized versions? Or do you have to delete the parent asset and all the versions together?

Bitmap files are not being thumbnailed (at least in my install), nor are they getting a valid width and height. There are other problems related to bmp's and previewing them, but I suspect these are all the same core issue. Png's, jpg's and gif's all work fine. This might be related to my setup since all I did was the quick Ubuntu install of the gd module. If more is required, then my setup is the problem.

**Summary**

Really, nice job on this code! Being able to group attachments in a particular node is an important addition to the framework. In my mind, the only thing I recommend to be resolved before merging is my database suggestion, just so that we don't feel we need to write some custom migration code to "fix" old versions at some point in the future. And I'd be willing to dig in on that if you agree. All the other issues relate to usability rather than functionality, so they shouldn't hold up the show if we want to get it released sooner rather than later.

**Comment by rchavik** [comment]
Hello Mike,

Thanks for the review. Really appreciate it.

> Icons for delete and un-register are a little inconsistent.

Yes.  Totally agree to improve the intent of the icons.

> - There is a paperclip icon that keeps coming up for me as I navigate through the browsers, uploaders, etc. I believe this is supposed to be present when we are using the wysiwyg editor
> - Before moving on, notice that the url contains a query param "editor=1". Next, click on List All Attachments, notice the "editor=1" is gone, then click on List Attachments, and the paperclip is now gone
> - Additionally in this flow, the trashcan appears in the popup when you are viewing the list of attachments registered with this content item

Yes, unfortunately. I was winging it as I added features.  All the clumsy URL query parameters, like "editor=1", "all=1", were attempts to try to cram as much functionality into the `browse()` action.

Maybe we should try to split the action sooner than later.

> One thing on the database side of things. I see the path field is consistent between the parent and the child asset, using the hashed version of the name in both cases. In contrast, the filename field uses the original filename for the parent, but a hashed version for the child. It might make sense for the filename field to be consistent between both parent and child as well.

I would prefer to keep the filename part in the `path` field as hash.   As for the `filename` field, I agree with you.  I could not recall exactly, but I think I took a shortcut since during the resize I do not have direct reference to the parent information.

> The number of versions field is empty in the browser. It only shows up when you use the content-related browser. I'm guessing this is intended to be the number of resized versions plus one for the original?

Yes. That is correct.

> Is there a way to delete just one of the resized versions? Or do you have to delete the parent asset and all the versions together?

I don't think so.  This functionality is not behaving correctly at this moment.  The trash icon is currently passed attachment id.  So it would delete the attachment and all its related assets. We need to create a separate one to delete a version and pass it the asset id.

> Bitmap files are not being thumbnailed (at least in my install), nor are they getting a valid width and height. There are other problems related to bmp's and previewing them, but I suspect these are all the same core issue. Png's, jpg's and gif's all work fine. This might be related to my setup since all I did was the quick Ubuntu install of the gd module. If more is required, then my setup is the problem.

At the time, I was not bothering to support BMP as I do not used personally.use them.   So it was not your setup.

> In my mind, the only thing I recommend to be resolved before merging is my database suggestion, just so that we don't feel we need to write some custom migration code to "fix" old versions at some point in the future. And I'd be willing to dig in on that if you agree. 

Are you referring on the content of 'filename` and `path` field? If so, please consider my above comment.

> All the other issues relate to usability rather than functionality, so they shouldn't hold up the show if we want to get it released sooner rather than later.

If you have improvements please go ahead and push directly into 3.1-asset branch.   We can rebase/tweak as needed.

Thanks again Mike

**Comment by miketallroth** [comment]
Hi Rachman.

> I would prefer to keep the filename part in the path field as hash. As for the filename field, I agree with you. I could not recall exactly, but I think I took a shortcut since during the resize I do not have direct reference to the parent information.

I agree with your stance on the database issue. The _path_ field should stay as-is, containing the hashed filename. The point I was trying to make was to say that we might need to provide a "migration" method from the current hashed _filename_ field to a future _filename_ field format (without the hash). That's pretty subtle though, and may never be needed. I dug into the code thinking it would be pretty simple, but went around the loop of StorageHandlers a couple times, and decided to pull out before getting totally confused. :)

So, for now, I'll try to make some commits to smooth the icons and other usability issues, and we can get it merged in. Before I get too far on that however, I had a question about how the croogo 3.x repo is structured, which I've opened in a separate issue. Please take a look at that and comment if you can.

thanks!

**Comment by rchavik** [comment]
> I dug into the code thinking it would be pretty simple, but went around the loop of StorageHandlers a couple times, and decided to pull out before getting totally confused. :)

I can relate. We would need to refactor this once this gets merged. Hopefully, more eyeballs will help.

**Comment by miketallroth** [comment]
I just pushed a new branch 3.1-assets-patch because there are a couple of items in there I wasn't sure about. I know they work, but wasn't sure about style. I felt we should discuss them a bit before I put them right on 3.1-assets. Maybe that's too conservative. In any case;

367582a Found that the tooltips need to be re-initialized upon ajax reload. I jammed in a call to Admin.form() which is a duplicate call of what's in the initializers Element (which does not get included on an ajax call). Don't know if there is a better way to accomplish the result. Perhaps the entire initializers Element should get included there as well. I didn't get deep into what all the other calls there do and if they are needed on a reload. Also, the newlines and spaces make it cleaner when looking at the generated source, but looks clunky in code.

ca5ead5 I needed to add 'admin' into the hard-coded string in Wysiwyg/js/wysiwyg.js for attachmentsPath otherwise I get an error message before even getting the attachment browser. Looks like there used to be code in the WysiwygHelper that overwrote the JS values, but that code has been removed. Is this adding to plugin coupling?

4a37e6b If I remove the 'editor' query param it prevents the paperclip from spuriously appearing as an admin action in the new asset process. On a related note, af923d9 I've confirmed when using CKEditor the paperclip gets removed unless I include a check specifically for the 'CKEditor' query param. This seems out of place, and should probably be replaced with a more generic 'editor' param maybe as part of the Wysiwyg plugin instead of the CKEditor instance.

Ok, here's the line between pragmatic and purist. The above is all stuff I think we can act on in the near-term. The stuff below is good (IMO), but tends to wander off into things that will take longer. Let me know which commits you'd like to merge right away and I'll get that done.

Mike


continuing on with the "big thinking"....

For example, I get this in the CKEditor chooser popup;
`.../admin/file-manager/attachments/browse?CKEditor=NodeBody&CKEditorFuncNum=1&langCode=en`
Maybe something like this could work more generically;
`.../admin/file-manager/attachments/browse?editor=1&wysiwyg=CKEditor&entityId=NodeBody...`

More thinking required on this one. I've got lots of thoughts about the wysiwyg chooser and how that should work. Kind of relates to my work on the Clinks plugin in Croogo 1.x that smoothed the use of the images within the wysiwyg previewer and the chooser previewer, as well as across deployment methods (VirtualHost, or Alias, or port hosted).

One thought is about the generation of the asset path. The Croogo.basePath provided to javascript ends with a slash, and the asset path in the database begins with a slash, so the resultant concatenation contains a double slash. I suspect the asset path starts with a slash because that tends to smooth out its addressing when you don't have good control over prefixing it properly (is it being rendered in the context of a layout, or a page, or block, or even deeper?). But it causes problems when trying to include the proper basePath.

Other questions come up like, "if I register five assets with a node, can I get a filtered list in the wysiwyg chooser that only shows those five assets?", and "can I also see the full list if I want to?" Or, "as an admin, can I choose to strictly limit the wysiwyg chooser to ONLY show those already registered with this node?" I could see arguments for at least a few of those.

**Comment by rchavik** [comment]
Hi Mike,

The above changes looks trivial and some I think I had used (367582acbce3b9dd7df333b2d82e33c7795f43ed) in other project (unpushed).  So, all good.

However, I think it maybe prudent to merge this into 4.0 instead?  If you agree, please go ahead and create the branch from 3.1 for this merge.

> One thought is about the generation of the asset path. The Croogo.basePath provided to javascript ends with a slash, and the asset path in the database begins with a slash, so the resultant concatenation contains a double slash. I suspect the asset path starts with a slash because that tends to smooth out its addressing when you don't have good control over prefixing it properly (is it being rendered in the context of a layout, or a page, or block, or even deeper?). But it causes problems when trying to include the proper basePath.

Maybe Croogo.basePath should not ends with a slash?

**Comment by rchavik** [comment]
Hi Mike,

The above changes looks trivial and some I think I had used (367582acbce3b9dd7df333b2d82e33c7795f43ed) in other project (unpushed).  So, all good.

However, I think it maybe prudent to merge this into 4.0 instead?  If you agree, please go ahead and create the branch from 3.1 for this merge. 

> One thought is about the generation of the asset path. The Croogo.basePath provided to javascript ends with a slash, and the asset path in the database begins with a slash, so the resultant concatenation contains a double slash. I suspect the asset path starts with a slash because that tends to smooth out its addressing when you don't have good control over prefixing it properly (is it being rendered in the context of a layout, or a page, or block, or even deeper?). But it causes problems when trying to include the proper basePath.

Maybe Croogo.basePath should not ends with a slash?

**Comment by miketallroth** [comment]
I created the 4.0 branch from 3.1.

I guess I don't have the context to know yet if it should go into 4.0 or a later 3.x branch. Scheduling this for 4.0 would give us more time to really work through some of the architectural issues we're starting to talk about, and let us get some of the other bug fixes in further 3.x releases. For that reason, I favor 4.0.

**Comment by rchavik** [comment]
I've fast-forwarded 4.0 to master and then merge your commits in 3.1-assets-patch.

**Comment by slightlychilled** [comment]
I've started some testing on this branch and it's looking pretty good. A couple of bugs and issues, but one thing that is not clear - when files are uploaded where are they located in the filesystem?

**Comment by rchavik** [comment]
> when files are uploaded where are they located in the filesystem?

In the current state, target upload directory is webroot/assets.

**Pull request closed without merging**
