### PR TITLE
wip - Js include order

### PR DESCRIPTION
**Pull request by miketallroth**
Include default scripts in HEAD section rather than body. This is somewhat a stylistic change, however order of external referenced scripts does matter when loading and running.

Render blocks early to allow scripts requested from blocks or elements in blocks to appear in HEAD. Without this, elements which try to include scripts in the 'script' block are rendered too late to be included in the `$this->Blocks->get('script')` call.

This seems like a simpler way of organizing script includes and helps to eliminate race conditions for loading js files. Developers can place script libraries in the 'script' block, ie. `['block'=>true]`, and inline script code in 'scriptBottom' block, ie. `['block'=>'scriptBottom']`.

As is, with the javascripts element getting rendered late (at the end of the default layout), it places important libraries (like jquery) after block element requested libraries or inline code. If the inline code needs jquery, it requires a custom layout in order for the code to get sequenced correctly.

### CODE REVIEW

**Comment by miketallroth** [comment]
Hi Rachman.

After further thought, this could be thought of as a breaking change if someone created a custom layout based on the existing core default layout. So, if you think moving this to a later release, I would be ok with that.

**Comment by rchavik** [comment]
Yes, agree.

Let's merge it into the 4.0 branch that was prepared for assets integration.

**Comment by rchavik** [comment]
Can you help testing on top of recent 4.0?

**Comment by rchavik** [comment]
@dakota this is also a good candidate for 4.0

**Pull request merged**
