### PR TITLE
Update date picker

### PR DESCRIPTION
**Pull request by dakota**
Been getting weird breakages with the bootstrap-datetimepicker that was used for datetime fields. Updates it to https://tempusdominus.github.io/bootstrap-4/ which is a bootstrap4 successor for it, and makes formatting, etc. a bit more predictable.

### CODE REVIEW

**Comment by rchavik** [comment]
Thanka. Will check in a couple of hours

**Comment by rchavik** [comment]
I'm getting `Undefined class constant 'ATOM'` error. Do we need to bump chronos or cakephp?

**Comment by rchavik** [comment]
I had to do this to make things work:

```diff --git a/Core/src/View/Widget/DateTimeWidget.php b/Core/src/View/Widget/DateTimeWidget.php
index 9d5a08b7..6c94bb0c 100644
--- a/Core/src/View/Widget/DateTimeWidget.php
+++ b/Core/src/View/Widget/DateTimeWidget.php
@@ -15,6 +15,7 @@ use Cake\Utility\Hash;
 use Cake\View\Form\ContextInterface;
 use Cake\View\Widget\DateTimeWidget as CakeDateTimeWidget;
 use Croogo\Extensions\CroogoTheme;
+use DateTime;
 use DateTimeInterface;
 
 class DateTimeWidget extends CakeDateTimeWidget
@@ -61,7 +62,7 @@ class DateTimeWidget extends CakeDateTimeWidget
         }
 
         if ($val instanceof DateTimeInterface) {
-            $val = $val->format(ChronosInterface::ATOM);
+            $val = $val->format(DateTime::ATOM);
         }
 
         $request = Router::getRequest();
```

**Comment by dakota** [comment]
Oh dear. I think I added that change without properly testing it

**Comment by rchavik** [comment]
Do you want to fix it up ?

**Comment by dakota** [comment]
Done :)

**Comment by rchavik** [comment]
Thanks

**Pull request merged**
